### ISSUE TITLE
Make junit / jira testcase matcher project agnostic

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-mro-jenkins-shared-library#101]
https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/2d8dfcf0b34efcf15ee028c577f0edc03b1a7ebb/src/org/ods/usecase/JiraUseCase.groovy#L363-L364

matches a jira issue (PLTFMDEV-551)  to the test below.

```
@Stepwise
class CustomerOrdersAcceptanceSpec extends GebReportingSpec {

    def "PLTFMDEV551_User buys some socks"() {
```

Now, supposed we change the project name, this will fail .. 
As we know the project name (from metadata.yml) - we should use it here to strip the issue key down to the number, rather than force people to code the project name into the testcase label. 

```
    def "551_User buys some socks"() {
```

should work as well then.

This way we can ship the entire validation project - and tell used, install it in whatever project you like, change metadata.yml and off you go :)

**Comment by metmajer** [comment]
Won't do as in most programming languages identifiers, including method names, cannot start with a number.
