### ISSUE TITLE
Merge into ods-jenkins-shared-library

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-mro-jenkins-shared-library#104]
I propose to merge this library into ods-jenkins-shared-library. Why?

* There's lots of code duplication (e.g. communicating with OpenShift), and this will increase soonish when we land the "release feature". Having two libraries will lead to inconsistencies.
* The MRO already depends heavily on the ods-jenkins-shared-library (stashed things, paths, names ..) and the integration is very brittle. Even ods-jenkins-shared-library has knowledge about the MRO lib (reading certain env vars) ...
* One library takes less effort to maintain.

I would propose to look at this for ODS 4.

@metmajer @clemensutschig @oalyman Thoughts?

**Comment by oalyman** [comment]
And on top of that reconsider what should be really part of the jenkins shared library.
Currently it is way too much "business logic" and with the limitations and drawbacks of what is possible in the pipelines (https://jenkins.io/blog/2017/02/01/pipeline-scalability-best-practice/) it makes development really slow and the implementation way more complex than it needs to be.

**Comment by metmajer** [comment]
We already had this discussion, and I am not convinced (yet).

* MRO Sharded Lib acts on top of components that requires non-sandboxed execution (Global Sharded Library)
* ODS Shared Lib acts inside a component and needs to restriction execution to a sandbox
* Both share a contract, but address two different concerns

I suggest moving duplicated code into another shared library.

**Comment by metmajer** [comment]
@oalyman we have been investigating a plugin-concept to externalize document generation. What's on your mind?

**Comment by michaelsauter** [comment]
Both ODS and MRO lib are global libraries by now - no sandbox restriction.

Moving shared logic in a third repo complicates management even further. We need to go simpler, not more complex.

Also, there is no real, explicit contract between the two repos right now - to be really honest, there are just assumptions from either side ...

**Comment by michaelsauter** [comment]
We're going to do this for v3. Initially, it will be just a merge into the repo, without aligning the code bases. We can do this step by step then.

**Comment by metmajer** [comment]
In order to keep the commit history intact in the new location, what about we attempt using `git merge --allow-unrelated-histories`? In the past, I have used this approach to merge an existing, upstream application into (on top of) a freshly deployed ODS component. This should do the trick here. @michaelsauter Thoughts?

**Comment by michaelsauter** [comment]
@metmajer No worries, I will do that.
