### ISSUE TITLE
MRO should inject / update environment / cluster url? into component DC during environment promotion

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-mro-jenkins-shared-library#189]
When components are promoted we need to inject somehow the environment / the cluster domain? - so components can e.g. put a URL together to the right environment ..  (e.g frontend js calling backend)

@michaelsauter  - any ideas from tailor perspective ... I guess we could have all quickstarters see a DC env param `environment` that one can the overwrite in the `.env` - but that only gets us this far...

**Comment by michaelsauter** [comment]
Currently, the intended way to do this is via the process described in https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/master/promotion-guide.adoc#customizing-release-bundle-creation.

For example, you use an environment variable to tell your frontend deployment where your backend deployment is. This environment variable is hardcoded, BUT if you add that value as a parameter in your .env files, then substitution will happen automatically on promotion.

Does that solve your use case or do you have something else in mind?

**Comment by clemensutschig** [comment]
@michaelsauter  - well, we would need to inject those variables (the content that is) - from external .. so they only idea I could envision is you define the vars in the DC in dev .. - and we then add them dynamically during deploy?

my idea would be - you define in your dev.env - `ODS_ENVIRONMENT` and `ODS_CLUSTER_ROUTE_URL` - and we inject those during phase `deploy` ... thoughts?

**Comment by clemensutschig** [comment]
ok - this will be simple. in case you have the cluster URL somewhere - we will replace it with the right url on import & export .. so one anyway would configure this in a config map / dc on dev .. and then move from there ... the same for the project name .. if configured - will be auto replaced

**Comment by clemensutschig** [comment]
closed by #189
