### ISSUE TITLE
add "antora" documentation

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-mro-jenkins-shared-library#24]
My understanding of the overall project documentation is that antora is used for bundling documentation of all repos. This repos isn't yet integrated into the ods-documentation repo and (as) it doesn't have antora enabled documentation.
Documentation should be moved into the Antora setup comparable with https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/docs/modules/ROOT/pages/index.adoc.

**Comment by metmajer** [comment]
I don't agree. This library is at the heart of the release manager quickstarter, and this quickstarter defines the behavior of this library. Also, this library is not meant to be used in other terms than being loaded by the release manager.

We have added Antora documentation for the release manager quickstarter just recently here: https://github.com/opendevstack/ods-quickstarters/pull/98.
