### ISSUE TITLE
Create a Zephyr Test Cycle for all Test Executions 

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-mro-jenkins-shared-library#32]
We want all test executions in the pipeline to be contained in Zephyr Test Cycles (when the Zephyr capability is activated).

The test cycle shall be:
- named by the environment we are operating in: `D`/`Q`/`P`
- the version should be set to the value in `MROPipelineUtil.getBuildParams().version`
- the build number value in the cycle should be filled with the pipeline run number

Note:
- a test cycle with the same version may already exist (as a pipeline may run multiple times for each version)

**Comment by metmajer** [comment]
@hrcornejo you will find the environment token `D`/`Q`/`P` to be applied in `MROPipelineUtil.getBuildParams().targetEnvironmentToken`.

Depends on #36

**Comment by metmajer** [comment]
@hrcornejo I have updated the requirements with the pipeline run number in the cycle's build number field

**Comment by hrcornejo** [comment]
@metmajer The Zephyr API doesn't have a method to update a cycle (where with every execution we would update the build number). Only it's possible to set the first time, when the cycle is created.
So or we don't reuse it and create a new one every time to fill this param or we can't do it.

**Comment by metmajer** [comment]
Let's create a cycle for each build number. I'll apply a patch. Otherwise LGTM!
