### ISSUE TITLE
mro should fail if sonarqube results are NOT available

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-mro-jenkins-shared-library#8]
we should really enforce sonarqube scanning - the only way I can think of (except to do it in the jenkins shared lib?) is here - where we generate the final docs

**Comment by michaelsauter** [comment]
I guess we have to move this to post-2.0. @clemensutschig Agree?

**Comment by metmajer** [comment]
If SonarQube scanning is to enforced, why not enforce it where the action is happening, i.e., in the ODS shared lib?

**Comment by michaelsauter** [comment]
In ODS 2, in each Jenkinsfile, one can now enable to fail when the SonarQube stage fails: https://github.com/opendevstack/ods-jenkins-shared-library/pull/154.

Real "enforcment" cannot happen anyway, as everyone can simply remove the stage or configure it differently. 

The only place I see where one can enforce this to some degree is where document generation happens - one could not do that when the results are not available ...

Given the timeframe, and the unclarity how/where this should be done, I am moving this issue off from ODS 2.

**Comment by metmajer** [comment]
@clemensutschig @michaelsauter 

Closing this as the behavior is already implemented in the v0.1.0 tag (and therefore part of ODS 1.2): https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/v0.1.0/vars/phaseBuild.groovy#L35-L44.
