### ISSUE TITLE
several typos in code comments iff vs. if

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-mro-jenkins-shared-library#9]
https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/941ecda6a85c66af6eecb47a36dc95d510c527a6/src/org/ods/usecase/LeVaDocumentUseCase.groovy#L67

**Comment by metmajer** [comment]
Not a typo at all. "iff" is an abbreviation for "if and only if".

**Comment by tbugfinder** [comment]
oh, didn't think it was meant like that.

**Comment by tbugfinder** [comment]
Here it could be if too.

https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/941ecda6a85c66af6eecb47a36dc95d510c527a6/src/org/ods/usecase/LeVaDocumentUseCase.groovy#L405
